In [2]:
import numpy as np
from math import sin
from scipy.linalg import eigh
from numpy.linalg import inv
from matplotlib import pyplot as plt

In [3]:
m = 0.008621 #kgm^2
m2 = 0.0010168
m3 = 0.0017045
k1 = 3e6 #Nm/rad
k2 = 3e6
omega = 160.8062 #rad/s
c1 = 0.00 #nms/rad
c2 = 0.00
F0 =0.000 #Nm
dof = 3

K = np.array([[k1,-k1, 0],[-k1,k1+k2, -k2],[0,-k2,k2]])
C = np.array([[c1,-c1, 0],[-c1,c1+c2, -c2],[0,-c2,c2]])
M = np.array([[5*m, 0, 0],[0, 0.5*m, 0],[0, 0, m]])
I = np.identity(dof)

A = np.zeros((2*dof, 2*dof))
B = np.zeros((2*dof, 2*dof))
Y = np.zeros((2*dof, 1))
F = np.zeros((2*dof, 1))

A[dof:2*dof, dof:2*dof] = M
A[0:dof, 0:dof] = I
B[dof:2*dof, 0:dof] = K
B[0:dof, dof:2*dof] = -I
B[dof:2*dof,dof:2*dof] = C
evals, evecs = eigh(K,M)
frequencies = np.sqrt(evals) #rad/s
frequencies_hz = frequencies/(2*np.pi) #Hz
#c_crit = 2 * np.sqrt(M.dot*K.dot)
#c_crit = 2 * np.sqrt(M.dot*K.dot)


print("Frequencies in rad/s")
print(frequencies)
print("-o-o-o-o-o-o-")
print("Frequencies in Hz")
print(frequencies_hz)
print("-o-o-o-o-o-o-")
print("Eigenvectors")
print(evecs)
omega_1 = frequencies[0]
omega_2 = frequencies[1]
omega_3 = frequencies[2]
print("-o-o-o-o-o-o-")
print("First omega: ", omega_1)
print("Second omega: ", omega_2)
print("Third omega: ", omega_3)
alpha1 = 1 #init displacement of Inertia 1 set to 1 as reference

#FIRST MODE
alpha2 = alpha1 - ((omega_2**2)/k1) * m * alpha1
alpha3 = alpha2 - ((omega_2**2)/k2) * (m * alpha1 + m2 * alpha2)
print("-o-o-o-o-o-o-")
print("Alpha2 equals: ", alpha2)
print("-o-o-o-o-o-o-")
print("Alpha3 equals: ", alpha3)
print("-o-o-o-o-o-o-")
#calculate the Torques
T1 = m * omega_2**2*alpha1
T2 = T1 + (m2) * alpha2 * omega_2**2
T3 = T2 + (m3) * alpha3 * omega_2**2

print("T1 equals: ", T1)
print("T2 equals: ", T2)
print("T3 equals: ", T3)

#SECOND MODE

Frequencies in rad/s
[2.63377359e-04 1.39645789e+04 4.01811572e+04]
-o-o-o-o-o-o-
Frequencies in Hz
[4.19178086e-05 2.22253176e+03 6.39502979e+03]
-o-o-o-o-o-o-
Eigenvectors
[[  4.2243948    2.22523976   0.63400429]
 [  4.2243948   -4.0097952  -14.07365195]
 [  4.2243948   -9.12130119   3.86680453]]
-o-o-o-o-o-o-
First omega:  0.00026337735932730513
Second omega:  13964.578882558659
Third omega:  40181.1571931167
-o-o-o-o-o-o-
Alpha2 equals:  0.43960780543711353
-o-o-o-o-o-o-
Alpha3 equals:  -0.14984035822303787
-o-o-o-o-o-o-
T1 equals:  1681176.5836886591
T2 equals:  1768344.490980454
T3 equals:  1718538.5103438378
